name: panoramicai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  toastification: ^3.0.3
  carousel_slider: ^5.1.1
  flutter_spinkit: ^5.2.2
  fl_chart: ^1.0.0
  image_picker: ^1.2.0
  image_cropper: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/































